# Generated by Django 3.1 on 2020-09-08 05:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bunrui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.CharField(default='ISDL', max_length=20)),
                ('borrower', models.TextField(blank=True, default='', null=True)),
                ('state', models.IntegerField(default=0)),
                ('remark', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 9, 8, 14, 31, 16, 166413))),
                ('bunrui', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='equipments.bunrui')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
