# Generated by Django 3.1 on 2020-09-11 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_auto_20200908_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 11, 15, 20, 28, 626816)),
        ),
    ]
